version: '2'
services:
  frontend:
    image: ghcr.io/coderbotorg/containers/frontend:latest
    restart: unless-stopped
    privileged: true
    network_mode: host

  backend:
    image: ghcr.io/coderbotorg/containers/backend:latest
    restart: unless-stopped
    privileged: true
    network_mode: host
    depends_on:
      - pigpio
    volumes:
      - "data:/coderbot/data"
      - "logs:/coderbot/logs"

  wifi:
    image: ghcr.io/coderbotorg/containers/wifi-connect:latest
    restart: unless-stopped
    privileged: true
    network_mode: host
    environment:
      DBUS_SYSTEM_BUS_ADDRESS: "unix:path=/host/run/dbus/system_bus_socket"
      PORTAL_LISTENING_PORT: 8080
    labels:
      io.balena.features.dbus: '1'
    cap_add:
      - NET_ADMIN

  pigpio:
    image: coderbot/alpine-pigpiod:arm32v7
    restart: unless-stopped
    privileged: true
    network_mode: host

volumes:
  data:
  logs: